// ─────────────────────────────────────────────────────────────────────────────
// §10-11 — أنماط الجينوم القضائيّ المستخرَجة من المراجع (بمصدرٍ وصفحة — لا اختلاق).
// مُولَّدٌ آليًّا من data/judicial-references/*.txt عبر scripts/extract-judicial-genome.py.
// كلّ نمطٍ مُثبَتٌ بصفحته في المرجع؛ طبقته JUDICIAL_METHOD/STYLE_REFERENCE — تؤسّس المنهج
// واللغة لا الحكم الحاليّ، فيلزمها فحص السريان (§6.1): currentLawCheckRequired = true.
// ─────────────────────────────────────────────────────────────────────────────
import type { JudicialPattern } from "./contracts";

export const REFERENCE_PATTERNS: readonly JudicialPattern[] = [
  {
    id: "REF-0001", code: "REF_0001", version: "0.1.0", status: "DRAFT",
    patternClass: "PROCEDURAL_SEQUENCE",
    sourceLayer: "JUDICIAL_METHOD_REFERENCE",
    sourceFileId: "khudayri-ijraat-ch2", sourcePage: 39,
    sourceSection: "مذكرة الإجراءات القضائية — الخضيري",
    normalizedPatternAr: "تُسمع الدعوى", semanticFunctionAr: "افتتاح سماع الدعوى",
    appliesToRoles: ["JUDGE","JUDICIAL_ASSISTANT"], appliesToDomains: [], appliesToStages: [],
    appliesToDocumentTypes: ["CLAIM_FORMULATION","ANSWER_FORMULATION","REASONING"],
    appliesWhen: ["عند انطباق مقامه في التسلسل الإجرائيّ"],
    prohibitedWhen: ["قبل التحقّق من موافقته للنظام السعوديّ الساري"],
    requiredAuthorityTypes: ["CURRENT_OFFICIAL_AUTHORITY"], currentLawCheckRequired: true,
    variables: [], positiveExamples: [], negativeExamples: [],
  },
  {
    id: "REF-0002", code: "REF_0002", version: "0.1.0", status: "DRAFT",
    patternClass: "PROCEDURAL_SEQUENCE",
    sourceLayer: "JUDICIAL_METHOD_REFERENCE",
    sourceFileId: "khudayri-ijraat-ch2", sourcePage: 10,
    sourceSection: "مذكرة الإجراءات القضائية — الخضيري",
    normalizedPatternAr: "تُعرض الدعوى", semanticFunctionAr: "عرض الدعوى على الخصم",
    appliesToRoles: ["JUDGE","JUDICIAL_ASSISTANT"], appliesToDomains: [], appliesToStages: [],
    appliesToDocumentTypes: ["CLAIM_FORMULATION","ANSWER_FORMULATION","REASONING"],
    appliesWhen: ["عند انطباق مقامه في التسلسل الإجرائيّ"],
    prohibitedWhen: ["قبل التحقّق من موافقته للنظام السعوديّ الساري"],
    requiredAuthorityTypes: ["CURRENT_OFFICIAL_AUTHORITY"], currentLawCheckRequired: true,
    variables: [], positiveExamples: [], negativeExamples: [],
  },
  {
    id: "REF-0003", code: "REF_0003", version: "0.1.0", status: "DRAFT",
    patternClass: "EVIDENCE_EXPRESSION",
    sourceLayer: "JUDICIAL_METHOD_REFERENCE",
    sourceFileId: "khudayri-ijraat-ch2", sourcePage: 43,
    sourceSection: "مذكرة الإجراءات القضائية — الخضيري",
    normalizedPatternAr: "فتُطلب البيّنة", semanticFunctionAr: "الانتقال إلى البيّنة",
    appliesToRoles: ["JUDGE","JUDICIAL_ASSISTANT"], appliesToDomains: [], appliesToStages: [],
    appliesToDocumentTypes: ["CLAIM_FORMULATION","ANSWER_FORMULATION","REASONING"],
    appliesWhen: ["عند انطباق مقامه في التسلسل الإجرائيّ"],
    prohibitedWhen: ["قبل التحقّق من موافقته للنظام السعوديّ الساري"],
    requiredAuthorityTypes: ["CURRENT_OFFICIAL_AUTHORITY"], currentLawCheckRequired: true,
    variables: [], positiveExamples: [], negativeExamples: [],
  },
  {
    id: "REF-0004", code: "REF_0004", version: "0.1.0", status: "DRAFT",
    patternClass: "CONDITIONAL_BRANCH",
    sourceLayer: "JUDICIAL_METHOD_REFERENCE",
    sourceFileId: "khudayri-ijraat-ch2", sourcePage: 64,
    sourceSection: "مذكرة الإجراءات القضائية — الخضيري",
    normalizedPatternAr: "فإن أحضر بيّنة", semanticFunctionAr: "فرع إحضار البيّنة",
    appliesToRoles: ["JUDGE","JUDICIAL_ASSISTANT"], appliesToDomains: [], appliesToStages: [],
    appliesToDocumentTypes: ["CLAIM_FORMULATION","ANSWER_FORMULATION","REASONING"],
    appliesWhen: ["عند انطباق مقامه في التسلسل الإجرائيّ"],
    prohibitedWhen: ["قبل التحقّق من موافقته للنظام السعوديّ الساري"],
    requiredAuthorityTypes: ["CURRENT_OFFICIAL_AUTHORITY"], currentLawCheckRequired: true,
    variables: [], positiveExamples: [], negativeExamples: [],
  },
  {
    id: "REF-0005", code: "REF_0005", version: "0.1.0", status: "DRAFT",
    patternClass: "OATH_EXPRESSION",
    sourceLayer: "JUDICIAL_METHOD_REFERENCE",
    sourceFileId: "khudayri-ijraat-ch2", sourcePage: 70,
    sourceSection: "مذكرة الإجراءات القضائية — الخضيري",
    normalizedPatternAr: "فإن حلف", semanticFunctionAr: "فرع الحلف",
    appliesToRoles: ["JUDGE","JUDICIAL_ASSISTANT"], appliesToDomains: [], appliesToStages: [],
    appliesToDocumentTypes: ["CLAIM_FORMULATION","ANSWER_FORMULATION","REASONING"],
    appliesWhen: ["عند انطباق مقامه في التسلسل الإجرائيّ"],
    prohibitedWhen: ["قبل التحقّق من موافقته للنظام السعوديّ الساري"],
    requiredAuthorityTypes: ["CURRENT_OFFICIAL_AUTHORITY"], currentLawCheckRequired: true,
    variables: [], positiveExamples: [], negativeExamples: [],
  },
  {
    id: "REF-0006", code: "REF_0006", version: "0.1.0", status: "DRAFT",
    patternClass: "OATH_EXPRESSION",
    sourceLayer: "JUDICIAL_METHOD_REFERENCE",
    sourceFileId: "khudayri-ijraat-ch2", sourcePage: 70,
    sourceSection: "مذكرة الإجراءات القضائية — الخضيري",
    normalizedPatternAr: "وإن نكل", semanticFunctionAr: "فرع النكول",
    appliesToRoles: ["JUDGE","JUDICIAL_ASSISTANT"], appliesToDomains: [], appliesToStages: [],
    appliesToDocumentTypes: ["CLAIM_FORMULATION","ANSWER_FORMULATION","REASONING"],
    appliesWhen: ["عند انطباق مقامه في التسلسل الإجرائيّ"],
    prohibitedWhen: ["قبل التحقّق من موافقته للنظام السعوديّ الساري"],
    requiredAuthorityTypes: ["CURRENT_OFFICIAL_AUTHORITY"], currentLawCheckRequired: true,
    variables: [], positiveExamples: [], negativeExamples: [],
  },
  {
    id: "REF-0007", code: "REF_0007", version: "0.1.0", status: "DRAFT",
    patternClass: "DISPOSITION_EXPRESSION",
    sourceLayer: "JUDICIAL_METHOD_REFERENCE",
    sourceFileId: "khudayri-ijraat-ch2", sourcePage: 10,
    sourceSection: "مذكرة الإجراءات القضائية — الخضيري",
    normalizedPatternAr: "يُحكم بثبوت", semanticFunctionAr: "الحكم بالثبوت",
    appliesToRoles: ["JUDGE","JUDICIAL_ASSISTANT"], appliesToDomains: [], appliesToStages: [],
    appliesToDocumentTypes: ["REASONING","DISPOSITION"],
    appliesWhen: ["عند انطباق مقامه في التسلسل الإجرائيّ"],
    prohibitedWhen: ["قبل التحقّق من موافقته للنظام السعوديّ الساري"],
    requiredAuthorityTypes: ["CURRENT_OFFICIAL_AUTHORITY"], currentLawCheckRequired: true,
    variables: [], positiveExamples: [], negativeExamples: [],
  },
  {
    id: "REF-0008", code: "REF_0008", version: "0.1.0", status: "DRAFT",
    patternClass: "DISPOSITION_EXPRESSION",
    sourceLayer: "JUDICIAL_METHOD_REFERENCE",
    sourceFileId: "khudayri-ijraat-ch2", sourcePage: 33,
    sourceSection: "مذكرة الإجراءات القضائية — الخضيري",
    normalizedPatternAr: "يُصرف النظر", semanticFunctionAr: "صرف النظر عن الدعوى",
    appliesToRoles: ["JUDGE","JUDICIAL_ASSISTANT"], appliesToDomains: [], appliesToStages: [],
    appliesToDocumentTypes: ["REASONING","DISPOSITION"],
    appliesWhen: ["عند انطباق مقامه في التسلسل الإجرائيّ"],
    prohibitedWhen: ["قبل التحقّق من موافقته للنظام السعوديّ الساري"],
    requiredAuthorityTypes: ["CURRENT_OFFICIAL_AUTHORITY"], currentLawCheckRequired: true,
    variables: [], positiveExamples: [], negativeExamples: [],
  },
  {
    id: "REF-0009", code: "REF_0009", version: "0.1.0", status: "DRAFT",
    patternClass: "ANSWER_FORMULATION",
    sourceLayer: "JUDICIAL_STYLE_REFERENCE",
    sourceFileId: "khudayri-ijraat-ch2", sourcePage: 59,
    sourceSection: "مذكرة الإجراءات القضائية — الخضيري",
    normalizedPatternAr: "فإن أقرّ", semanticFunctionAr: "فرع الإقرار",
    appliesToRoles: ["JUDGE","JUDICIAL_ASSISTANT"], appliesToDomains: [], appliesToStages: [],
    appliesToDocumentTypes: ["CLAIM_FORMULATION","ANSWER_FORMULATION","REASONING"],
    appliesWhen: ["عند انطباق مقامه في التسلسل الإجرائيّ"],
    prohibitedWhen: ["قبل التحقّق من موافقته للنظام السعوديّ الساري"],
    requiredAuthorityTypes: ["CURRENT_OFFICIAL_AUTHORITY"], currentLawCheckRequired: true,
    variables: [], positiveExamples: [], negativeExamples: [],
  },
  {
    id: "REF-0010", code: "REF_0010", version: "0.1.0", status: "DRAFT",
    patternClass: "ANSWER_FORMULATION",
    sourceLayer: "JUDICIAL_STYLE_REFERENCE",
    sourceFileId: "khudayri-ijraat-ch2", sourcePage: 10,
    sourceSection: "مذكرة الإجراءات القضائية — الخضيري",
    normalizedPatternAr: "أو صادَق", semanticFunctionAr: "المصادقة",
    appliesToRoles: ["JUDGE","JUDICIAL_ASSISTANT"], appliesToDomains: [], appliesToStages: [],
    appliesToDocumentTypes: ["CLAIM_FORMULATION","ANSWER_FORMULATION","REASONING"],
    appliesWhen: ["عند انطباق مقامه في التسلسل الإجرائيّ"],
    prohibitedWhen: ["قبل التحقّق من موافقته للنظام السعوديّ الساري"],
    requiredAuthorityTypes: ["CURRENT_OFFICIAL_AUTHORITY"], currentLawCheckRequired: true,
    variables: [], positiveExamples: [], negativeExamples: [],
  },
  {
    id: "REF-0011", code: "REF_0011", version: "0.1.0", status: "DRAFT",
    patternClass: "ISSUE_PRESENTATION",
    sourceLayer: "JUDICIAL_STYLE_REFERENCE",
    sourceFileId: "khudayri-ijraat-ch2", sourcePage: 38,
    sourceSection: "مذكرة الإجراءات القضائية — الخضيري",
    normalizedPatternAr: "وعليه العمل", semanticFunctionAr: "ترجيح ما عليه العمل",
    appliesToRoles: ["JUDGE","JUDICIAL_ASSISTANT"], appliesToDomains: [], appliesToStages: [],
    appliesToDocumentTypes: ["CLAIM_FORMULATION","ANSWER_FORMULATION","REASONING"],
    appliesWhen: ["عند انطباق مقامه في التسلسل الإجرائيّ"],
    prohibitedWhen: ["قبل التحقّق من موافقته للنظام السعوديّ الساري"],
    requiredAuthorityTypes: ["CURRENT_OFFICIAL_AUTHORITY"], currentLawCheckRequired: true,
    variables: [], positiveExamples: [], negativeExamples: [],
  },
  {
    id: "REF-0012", code: "REF_0012", version: "0.1.0", status: "DRAFT",
    patternClass: "BENEFIT_PRESENTATION",
    sourceLayer: "JUDICIAL_STYLE_REFERENCE",
    sourceFileId: "khudayri-ijraat-ch2", sourcePage: 11,
    sourceSection: "مذكرة الإجراءات القضائية — الخضيري",
    normalizedPatternAr: "الفوائد", semanticFunctionAr: "عرض الفوائد",
    appliesToRoles: ["JUDGE","JUDICIAL_ASSISTANT"], appliesToDomains: [], appliesToStages: [],
    appliesToDocumentTypes: ["CLAIM_FORMULATION","ANSWER_FORMULATION","REASONING"],
    appliesWhen: ["عند انطباق مقامه في التسلسل الإجرائيّ"],
    prohibitedWhen: ["قبل التحقّق من موافقته للنظام السعوديّ الساري"],
    requiredAuthorityTypes: ["CURRENT_OFFICIAL_AUTHORITY"], currentLawCheckRequired: true,
    variables: [], positiveExamples: [], negativeExamples: [],
  },
];
