#!/usr/bin/env bash
# Cloud Agent install — idempotent bootstrap for the Hakeem platform.
# Runs after the repository is checked out. Safe to run repeatedly.
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_DIR"

PG_VERSION="16"
PG_CLUSTER="main"
DB_NAME="hakeem"
DB_USER="hakeem"
DB_PASSWORD="hakeem_password"

echo "[install] Ensuring PostgreSQL ${PG_VERSION} + pgvector are installed..."
if ! dpkg -s "postgresql-${PG_VERSION}" >/dev/null 2>&1 \
  || ! dpkg -s "postgresql-${PG_VERSION}-pgvector" >/dev/null 2>&1; then
  sudo apt-get update -qq
  sudo apt-get install -y -qq "postgresql-${PG_VERSION}" "postgresql-${PG_VERSION}-pgvector"
fi

echo "[install] Ensuring the PostgreSQL cluster is running..."
if ! pg_lsclusters -h 2>/dev/null | awk '{print $4}' | grep -q "online"; then
  sudo pg_ctlcluster "${PG_VERSION}" "${PG_CLUSTER}" start || true
fi
# Wait for the socket to accept connections.
for _ in $(seq 1 30); do
  if sudo -u postgres pg_isready -q; then break; fi
  sleep 1
done

echo "[install] Ensuring database role, database, and vector extension..."
sudo -u postgres psql -v ON_ERROR_STOP=1 <<SQL
DO \$\$ BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname='${DB_USER}') THEN
    CREATE ROLE ${DB_USER} LOGIN PASSWORD '${DB_PASSWORD}';
  END IF;
END \$\$;
SQL
if ! sudo -u postgres psql -tAc "SELECT 1 FROM pg_database WHERE datname='${DB_NAME}'" | grep -q 1; then
  sudo -u postgres createdb -O "${DB_USER}" "${DB_NAME}"
fi
sudo -u postgres psql -d "${DB_NAME}" -v ON_ERROR_STOP=1 \
  -c "ALTER SCHEMA public OWNER TO ${DB_USER};" \
  -c "GRANT ALL ON SCHEMA public TO ${DB_USER};" \
  -c "CREATE EXTENSION IF NOT EXISTS vector;"

echo "[install] Ensuring local .env exists (secrets/env vars can override)..."
if [ ! -f .env ]; then
  SECRET="$(openssl rand -base64 32)"
  cat > .env <<ENV
# Auto-generated by .cursor/install.sh for the Cloud Agent dev environment.
DATABASE_URL="postgresql://${DB_USER}:${DB_PASSWORD}@127.0.0.1:5432/${DB_NAME}?schema=public"
NEXTAUTH_SECRET="${SECRET}"
AUTH_SECRET="${SECRET}"
NEXT_PUBLIC_SITE_URL="http://localhost:3000"
NEXTAUTH_URL="http://localhost:3000"
INITIAL_ADMIN_EMAIL="admin@hakeem.local"
INITIAL_ADMIN_PASSWORD="Hakeem-Admin-1703!"
AI_PROVIDER="mock"
SEARCH_PROVIDER_MODE="postgres"
OWNER_BOOTSTRAP_PASSWORD="Qalam-1703!"
# Dev-only: enables the internal owner login gate at /internal/owner-gate.
OWNER_EMERGENCY_LOGIN_ENABLED="true"
ENV
fi

echo "[install] Installing npm dependencies..."
if [ -f package-lock.json ]; then
  npm ci
else
  npm install
fi

echo "[install] Generating Prisma client and syncing schema..."
npm run db:generate
# --accept-data-loss keeps this step idempotent: on a fresh DB it is a no-op, and on
# re-runs it only reconciles ephemeral runtime tables (recreated by the app at boot).
# Prisma-managed tables such as legal_articles are in the schema and are preserved.
npx prisma db push --accept-data-loss --skip-generate

echo "[install] Seeding the legal library if the database is empty..."
ARTICLE_COUNT="$(sudo -u postgres psql -d "${DB_NAME}" -tAc \
  "SELECT count(*) FROM legal_articles" 2>/dev/null || echo 0)"
if [ "${ARTICLE_COUNT:-0}" -lt 1 ]; then
  npm run db:seed
else
  echo "[install] Legal library already seeded (${ARTICLE_COUNT} articles); skipping."
fi

echo "[install] Done."
