// خريطة الأدوار×الصلاحيات الأساسية — بلا اعتماد على Prisma (آمن للواجهة والخادم).

export type AppRole = "SYSTEM_ADMIN" | "LAWYER" | "TRAINER" | "TRAINEE";

export type Permission =
  | "CONSULTATIONS_FULL"
  | "CONSULTATIONS_LIMITED"
  | "SIMULATIONS_USE"
  | "TRAINING_USE"
  | "TRAINING_MANAGE"
  | "LIBRARY_READ"
  | "LEGAL_CORE_VIEW"
  | "LEGAL_CORE_EDIT"
  | "LEGAL_CORE_ADMIN"
  | "ATTACHMENTS_FULL"
  | "ATTACHMENTS_LIMITED"
  | "USERS_MANAGE"
  | "ADMIN_REPORTS_VIEW"
  | "GOVERNANCE_AUDIT_VIEW";

export const ROLE_PERMISSIONS: Record<AppRole, Permission[]> = {
  SYSTEM_ADMIN: [
    "CONSULTATIONS_FULL",
    "SIMULATIONS_USE",
    "TRAINING_USE",
    "TRAINING_MANAGE",
    "LIBRARY_READ",
    "LEGAL_CORE_VIEW",
    "LEGAL_CORE_EDIT",
    "LEGAL_CORE_ADMIN",
    "ATTACHMENTS_FULL",
    "USERS_MANAGE",
    "ADMIN_REPORTS_VIEW",
    "GOVERNANCE_AUDIT_VIEW",
  ],
  LAWYER: [
    "CONSULTATIONS_FULL",
    "SIMULATIONS_USE",
    "TRAINING_USE",
    "LIBRARY_READ",
    "LEGAL_CORE_VIEW",
    "ATTACHMENTS_FULL",
  ],
  TRAINER: [
    "SIMULATIONS_USE",
    "TRAINING_USE",
    "TRAINING_MANAGE",
    "LIBRARY_READ",
    "LEGAL_CORE_VIEW",
    "ATTACHMENTS_FULL",
    "ADMIN_REPORTS_VIEW",
  ],
  TRAINEE: [
    "CONSULTATIONS_LIMITED",
    "SIMULATIONS_USE",
    "TRAINING_USE",
    "LIBRARY_READ",
    "LEGAL_CORE_VIEW",
    "ATTACHMENTS_LIMITED",
  ],
};
